### ISSUE TITLE
admintool.sh problem: TypeError: 'zip' object does not support item deletion

### ISSUE THREAD

**Issue by mingrui** [cryptape/cita#142]
Python 3.6.3
`make debug` builds successfully

```
workspace/cita$ admintool.sh 
Step 1: ********************************************************
Start generating private Key for Node 0 !
[PrivateKey Path] :  /media/mingrui/960EVO/workspace/cita/node0
End generating private Key for Node 0 !
Start creating Network Node 0 Configuration!
Traceback (most recent call last):
  File "/media/mingrui/960EVO/workspace/cita/target/install/scripts/admintool/create_network_config.py", line 34, in <module>
    main()
  File "/media/mingrui/960EVO/workspace/cita/target/install/scripts/admintool/create_network_config.py", line 22, in main
    del ip_list[nid]
TypeError: 'zip' object does not support item deletion
```

**Comment by u2** [comment]
Only python2.7 are supported.
