### ISSUE TITLE
This is a bug

### ISSUE THREAD

**Issue by zhxy123** [cryptape/cita#172]
```
2018-07-04T05:07:43.954864099+00:00 - ERROR - Error in reading loop: Protocol("Connection reset by peer (os error 104)")
2018-07-04T05:07:43.957530230+00:00 - ERROR - Error consuming Protocol("Connection reset by peer (os error 104)")
2018-07-04T05:07:43.958573114+00:00 - ERROR - Error dispatching closing packet to a channel
2018-07-04T05:07:44.058057687+00:00 - ERROR - 
============================
stack backtrace:
   0:     0x55b75ecd0d25 - backtrace::backtrace::libunwind::trace::h5fd4cc63650da222
                        at /opt/.cargo/registry/src/mirrors.ustc.edu.cn-12df342d903acd47/backtrace-0.3.6/src/backtrace/libunwind.rs:53
                         - backtrace::backtrace::trace::hdc4a854af22ec245
                        at /opt/.cargo/registry/src/mirrors.ustc.edu.cn-12df342d903acd47/backtrace-0.3.6/src/backtrace/mod.rs:42
   1:     0x55b75eccb70e - backtrace::capture::Backtrace::new_unresolved::h3a0d808bad6c69a5
                        at /opt/.cargo/registry/src/mirrors.ustc.edu.cn-12df342d903acd47/backtrace-0.3.6/src/capture.rs:88
   2:     0x55b75eccb64d - backtrace::capture::Backtrace::new::ha88481038c6daa72
                        at /opt/.cargo/registry/src/mirrors.ustc.edu.cn-12df342d903acd47/backtrace-0.3.6/src/capture.rs:63
   3:     0x55b75e8ffa0d - panic_hook::panic_hook::h5dbe4e66376fe369
                        at /opt/.cargo/git/checkouts/cita-common-1aad419f3e80ba17/2752e22/panic_hook/src/lib.rs:51
   4:     0x55b75e900227 - core::ops::function::Fn::call::hbcaefdbbf754f1db
                        at /checkout/src/libcore/ops/function.rs:73
   5:     0x55b75eeb5d65 - std::panicking::rust_panic_with_hook::hc7c9a2f0d99e47e1
                        at libstd/panicking.rs:467
   6:     0x55b75eeb58ec - std::panicking::begin_panic_fmt::h4d3f8afad2489977
                        at libstd/panicking.rs:350
   7:     0x55b75eeb58b1 - rust_begin_unwind
                        at libstd/panicking.rs:328
   8:     0x55b75eefffd2 - core::panicking::panic_fmt::h5ba72226afe9877e
                        at libcore/panicking.rs:71
   9:     0x55b75e30342b - core::result::unwrap_failed::h8e338bf961aaf42d
                        at /checkout/src/libcore/macros.rs:26
  10:     0x55b75e30193d - <core::result::Result<T, E>>::unwrap::hb12a6f3eded9ccf0
                        at /checkout/src/libcore/result.rs:782
  11:     0x55b75e29fe80 - cita_network::main::{{closure}}::ha5b1fb7cf346dc8e
                        at cita-network/src/main.rs:241
  12:     0x55b75e2adbfa - std::sys_common::backtrace::__rust_begin_short_backtrace::heb728656f727ec89
                        at /checkout/src/libstd/sys_common/backtrace.rs:136
  13:     0x55b75e22477f - std::thread::Builder::spawn::{{closure}}::{{closure}}::ha8ad6801e11aa706
                        at /checkout/src/libstd/thread/mod.rs:409
  14:     0x55b75e278f6a - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h75884c809f4d2dbb
                        at /checkout/src/libstd/panic.rs:305
  15:     0x55b75e251fbf - std::panicking::try::do_call::h98062d424126b860
                        at /checkout/src/libstd/panicking.rs:310
  16:     0x55b75eed4869 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:105
  17:     0x55b75e25159e - std::panicking::try::h4c37889c1a3ee36e
                        at /checkout/src/libstd/panicking.rs:289
  18:     0x55b75e27903a - std::panic::catch_unwind::h55312cca3f1931fc
                        at /checkout/src/libstd/panic.rs:374
  19:     0x55b75e224009 - std::thread::Builder::spawn::{{closure}}::hd7d87f988d43f4a9
                        at /checkout/src/libstd/thread/mod.rs:408
  20:     0x55b75e2249af - <F as alloc::boxed::FnBox<A>>::call_box::h1d651d4c39ca06af
                        at /checkout/src/liballoc/boxed.rs:638
  21:     0x55b75eec64aa - <alloc::boxed::Box<alloc::boxed::FnBox<A, Output$u3d$R$GT$$u20$$u2b$$u20$$u27$a$GT$$u20$as$u20$core..ops..function..FnOnce$LT$A$GT$$GT$::call_once::h162c38d561c9dfac
                        at /checkout/src/liballoc/boxed.rs:648
                         - std::sys_common::thread::start_thread::h798b0437f4b504e5
                        at libstd/sys_common/thread.rs:24
  22:     0x55b75eeb31e5 - std::sys::unix::thread::Thread::new::thread_start::hf58dec18aa478933
                        at libstd/sys/unix/thread.rs:90
  23:     0x7f82767d76da - start_thread
  24:     0x7f82762e888e - __clone
  25:                0x0 - <unknown>

position:
Thread <unnamed> panicked at called `Result::unwrap()` on an `Err` value: RecvError, libcore/result.rs:945
```

**Comment by EighteenZi** [comment]
Would you please descripe the problem more clearly? 
What did you do before the process paniced?

**Comment by EighteenZi** [comment]
Long time no receive any more reply.
This issue is gonna be closed.
