### ISSUE TITLE
panic while running stSystemOperationsTest

### ISSUE THREAD

**Issue by ouwenkg** [cryptape/cita#451]
## Description

[Description of the issue]

Panic occured while running [CallToNameRegistratorNotMuchMemory0.json](https://github.com/cryptape/cita-testdata/blob/master/GeneralStateTests/stSystemOperationsTest/CallToNameRegistratorNotMuchMemory0.json)

Panic info:
```
hread 'main' panicked at 'index 987654 out of range for slice of length 64', src/libcore/slice/mod.rs:2341:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   6: rust_begin_unwind
             at src/libstd/panicking.rs:312
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::slice::slice_index_len_fail
             at src/libcore/slice/mod.rs:2341
   9: <core::ops::range::Range<usize> as core::slice::SliceIndex<[T]>>::index
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libcore/slice/mod.rs:2506
  10: core::slice::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libcore/slice/mod.rs:2323
  11: <alloc::vec::Vec<T> as core::ops::index::Index<I>>::index
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/liballoc/vec.rs:1678
  12: <evm::interpreter::Interpreter<Cost> as evm::evm::Evm>::exec::{{closure}}
             at cita-executor/evm/src/interpreter/mod.rs:189
  13: <core::option::Option<T>>::map
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libcore/option.rs:414
  14: <evm::interpreter::Interpreter<Cost> as evm::evm::Evm>::exec
             at cita-executor/evm/src/interpreter/mod.rs:189
  15: <core_executor::executive::Executive<'a, B>>::exec_vm
             at cita-executor/core/src/executive.rs:572
  16: <core_executor::executive::Executive<'a, B>>::call_evm_contract
             at cita-executor/core/src/executive.rs:875
  17: <core_executor::executive::Executive<'a, B>>::call
             at cita-executor/core/src/executive.rs:679
  18: <core_executor::executive::Executive<'a, B>>::transact_with_tracer
             at cita-executor/core/src/executive.rs:514
  19: <core_executor::executive::Executive<'a, B>>::transact
             at cita-executor/core/src/executive.rs:212
  20: <core_executor::state::State<B>>::apply
             at cita-executor/core/src/state/mod.rs:768
  21: state_test::test_json_file
             at tests/state_test/src/main.rs:95
  22: state_test::test_json_path
             at tests/state_test/src/main.rs:134
  23: state_test::test_json_path
             at tests/state_test/src/main.rs:131
  24: state_test::main
             at tests/state_test/src/main.rs:162
  25: std::rt::lang_start::{{closure}}
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libstd/rt.rs:64
  26: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:297
  27: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:92
  28: std::rt::lang_start_internal
             at src/libstd/panicking.rs:276
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  29: std::rt::lang_start
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libstd/rt.rs:64
  30: main
  31: __libc_start_main
  32: _start

```

## Steps to Reproduce

1. [First Step]
```
$ cd cita/tests/json_test/state_test/
```
2. [Second Step]
```
$ test_json_path(r"./tests/jsondata/GeneralStateTests/stSystemOperationsTest");
```
**Expected behavior**: [What you expect to happen]

passed

**Actual behavior**: [What actually happens]

panic

**Reproduce how often**: [What percentage of the time does it reproduce?]

ever

## Versions

Latest

## Additional Information

#366

**Comment by ouwenkg** [comment]
## 暂存

panic 根据日志定位问题:  evm trace 过程出现数组越界问题:

https://github.com/cryptape/cita/blob/debug_state/cita-executor/evm/src/interpreter/mod.rs#L199

```
if trace_executed && mem_written.unwrap_or_default().0 < self.mem.len() {
                ext.trace_executed(
                    gasometer.current_gas.as_u256(),
                    stack.peek_top(info.ret),
                    mem_written.map(|(o, s)| (o, &(self.mem[o..(o + s)]))),
                    store_written,
                );
            }
````
`mem_written.map(|(o, s)| (o, &(self.mem[o..(o + s)]))),` map 里 mem 的最大长度是 64, 而 o 的值是 987654. 出现了 panic 问题.

修正: 
```
if trace_executed && mem_written.unwrap_or_default().0 < self.mem.len() {
                ext.trace_executed(
                    gasometer.current_gas.as_u256(),
                    stack.peek_top(info.ret),
                    mem_written.map(|(o, s)| (o, &(self.mem[o..(o + s)]))),
                    store_written,
                );
            }
```

分析:

来张手绘图
![webwxgetmsgimg (1)](https://user-images.githubusercontent.com/11801722/57226206-0cb6c300-7041-11e9-9311-d2b678575f6e.jpeg)

粘贴个全部的日志信息吧:

```
      Running `target/debug/state_test`
[2019-05-06T12:21:05Z DEBUG core_executor::state] ============> commit key=0x945304eb96065b2a98b57a48a06ae28d285a71b5
[2019-05-06T12:21:05Z DEBUG core_executor::state] ============> commit key=0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b
[2019-05-06T12:21:05Z DEBUG core_executor::state] ============> commit key=0x095e7baea6a6c7c4c2dfeb977efac326af552d87
[2019-05-06T12:21:05Z ERROR core_executor::contracts::solc::price_manager] Use default quota price
[2019-05-06T12:21:05Z DEBUG core_executor::state::account] state.inc_nonce
[2019-05-06T12:21:05Z DEBUG core_executor::state] state.sub_balance a= 0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b, decr= 0x493e0
[2019-05-06T12:21:05Z DEBUG core_executor::executive] state.checkpoint
[2019-05-06T12:21:05Z DEBUG core_executor::executive] payment_required in call: true, value: Transfer(0x186a0), sender: 0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b, to: 0x095e7baea6a6c7c4c2dfeb977efac326af552d87, gas: 0x441d8, gas_price: 0x1
[2019-05-06T12:21:05Z DEBUG core_executor::state] state.sub_balance a= 0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b, decr= 0x186a0
[2019-05-06T12:21:05Z DEBUG core_executor::state] transfer balance process:
[2019-05-06T12:21:05Z DEBUG core_executor::state] state.sub_balance a= 0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b, decr= 100000
[2019-05-06T12:21:05Z DEBUG core_executor::state] state.add_balance a=0x095e…2d87, incr=100000
[2019-05-06T12:21:05Z DEBUG core_executor::executive] economical model in vm: Charge
[2019-05-06T12:21:05Z DEBUG evm::interpreter] [OP] "PUSH32" gas=279000
[2019-05-06T12:21:05Z DEBUG evm::interpreter] [Gas] - 3
[2019-05-06T12:21:05Z TRACE evm::interpreter] store_write: None, mem_written: None, mem.len(): 0
[2019-05-06T12:21:05Z DEBUG evm::interpreter] [OP] "PUSH1" gas=278997
[2019-05-06T12:21:05Z DEBUG evm::interpreter] [Gas] - 3
[2019-05-06T12:21:05Z TRACE evm::interpreter] store_write: None, mem_written: None, mem.len(): 0
[2019-05-06T12:21:05Z DEBUG evm::interpreter] [OP] "MSTORE" gas=278994
[2019-05-06T12:21:05Z DEBUG evm::interpreter] ==> instruct 82 1> first element: 0, second element: 32
[2019-05-06T12:21:05Z DEBUG evm::interpreter] [Gas] - 6
[2019-05-06T12:21:05Z TRACE evm::interpreter] store_write: None, mem_written: Some((0, 32)), mem.len(): 32
[2019-05-06T12:21:05Z DEBUG evm::interpreter] [OP] "PUSH32" gas=278988
[2019-05-06T12:21:05Z DEBUG evm::interpreter] [Gas] - 3
[2019-05-06T12:21:05Z TRACE evm::interpreter] store_write: None, mem_written: None, mem.len(): 32
[2019-05-06T12:21:05Z DEBUG evm::interpreter] [OP] "PUSH1" gas=278985
[2019-05-06T12:21:05Z DEBUG evm::interpreter] [Gas] - 3
[2019-05-06T12:21:05Z TRACE evm::interpreter] store_write: None, mem_written: None, mem.len(): 32
[2019-05-06T12:21:05Z DEBUG evm::interpreter] [OP] "MSTORE" gas=278982
[2019-05-06T12:21:05Z DEBUG evm::interpreter] ==> instruct 82 1> first element: 32, second element: 32
[2019-05-06T12:21:05Z DEBUG evm::interpreter] [Gas] - 6
[2019-05-06T12:21:05Z TRACE evm::interpreter] store_write: None, mem_written: Some((32, 32)), mem.len(): 64
[2019-05-06T12:21:05Z DEBUG evm::interpreter] [OP] "PUSH1" gas=278976
[2019-05-06T12:21:05Z DEBUG evm::interpreter] [Gas] - 3
[2019-05-06T12:21:05Z TRACE evm::interpreter] store_write: None, mem_written: None, mem.len(): 64
[2019-05-06T12:21:05Z DEBUG evm::interpreter] [OP] "PUSH3" gas=278973
[2019-05-06T12:21:05Z DEBUG evm::interpreter] [Gas] - 3
[2019-05-06T12:21:05Z TRACE evm::interpreter] store_write: None, mem_written: None, mem.len(): 64
[2019-05-06T12:21:05Z DEBUG evm::interpreter] [OP] "PUSH1" gas=278970
[2019-05-06T12:21:05Z DEBUG evm::interpreter] [Gas] - 3
[2019-05-06T12:21:05Z TRACE evm::interpreter] store_write: None, mem_written: None, mem.len(): 64
[2019-05-06T12:21:05Z DEBUG evm::interpreter] [OP] "PUSH1" gas=278967
[2019-05-06T12:21:05Z DEBUG evm::interpreter] [Gas] - 3
[2019-05-06T12:21:05Z TRACE evm::interpreter] store_write: None, mem_written: None, mem.len(): 64
[2019-05-06T12:21:05Z DEBUG evm::interpreter] [OP] "PUSH1" gas=278964
[2019-05-06T12:21:05Z DEBUG evm::interpreter] [Gas] - 3
[2019-05-06T12:21:05Z TRACE evm::interpreter] store_write: None, mem_written: None, mem.len(): 64
[2019-05-06T12:21:05Z DEBUG evm::interpreter] [OP] "PUSH20" gas=278961
[2019-05-06T12:21:05Z DEBUG evm::interpreter] [Gas] - 3
[2019-05-06T12:21:05Z TRACE evm::interpreter] store_write: None, mem_written: None, mem.len(): 64
[2019-05-06T12:21:05Z DEBUG evm::interpreter] [OP] "PUSH2" gas=278958
[2019-05-06T12:21:05Z DEBUG evm::interpreter] [Gas] - 3
[2019-05-06T12:21:05Z TRACE evm::interpreter] store_write: None, mem_written: None, mem.len(): 64

[2019-05-06T12:21:05Z DEBUG evm::interpreter] [OP] "CALL" gas=278955
`[2019-05-06T12:21:05Z DEBUG evm::interpreter] ==> instruct 241 5> first element: 987654, second element: 0`
[2019-05-06T12:21:05Z DEBUG evm::interpreter] [Gas] - 10200
[2019-05-06T12:21:05Z DEBUG core_executor::executive] state.checkpoint

[2019-05-06T12:21:05Z DEBUG core_executor::executive] payment_required in call: true, value: Transfer(0x17), sender: 0x095e7baea6a6c7c4c2dfeb977efac326af552d87, to: 0x945304eb96065b2a98b57a48a06ae28d285a71b5, gas: 0xaf0, gas_price: 0x1
[2019-05-06T12:21:05Z DEBUG core_executor::state] state.sub_balance a= 0x095e7baea6a6c7c4c2dfeb977efac326af552d87, decr= 0x17
[2019-05-06T12:21:05Z DEBUG core_executor::state] transfer balance process:
[2019-05-06T12:21:05Z DEBUG core_executor::state] state.sub_balance a= 0x095e7baea6a6c7c4c2dfeb977efac326af552d87, decr= 23
[2019-05-06T12:21:05Z DEBUG core_executor::state] state.add_balance a=0x9453…71b5, incr=23
[2019-05-06T12:21:05Z DEBUG core_executor::executive] economical model in vm: Charge
[2019-05-06T12:21:05Z DEBUG evm::interpreter] [OP] "PUSH1" gas=2800
[2019-05-06T12:21:05Z DEBUG evm::interpreter] [Gas] - 3
[2019-05-06T12:21:05Z TRACE evm::interpreter] store_write: None, mem_written: None, mem.len(): 0
[2019-05-06T12:21:05Z DEBUG evm::interpreter] [OP] "CALLDATALOAD" gas=2797
[2019-05-06T12:21:05Z DEBUG evm::interpreter] [Gas] - 3
[2019-05-06T12:21:05Z TRACE evm::interpreter] store_write: None, mem_written: None, mem.len(): 0
[2019-05-06T12:21:05Z DEBUG evm::interpreter] [OP] "SLOAD" gas=2794
[2019-05-06T12:21:05Z DEBUG evm::interpreter] [Gas] - 200
[2019-05-06T12:21:05Z TRACE evm::interpreter] store_write: None, mem_written: None, mem.len(): 0
[2019-05-06T12:21:05Z DEBUG evm::interpreter] [OP] "ISZERO" gas=2594
[2019-05-06T12:21:05Z DEBUG evm::interpreter] [Gas] - 3
[2019-05-06T12:21:05Z TRACE evm::interpreter] store_write: None, mem_written: None, mem.len(): 0
[2019-05-06T12:21:05Z DEBUG evm::interpreter] [OP] "PUSH1" gas=2591
[2019-05-06T12:21:05Z DEBUG evm::interpreter] [Gas] - 3
[2019-05-06T12:21:05Z TRACE evm::interpreter] store_write: None, mem_written: None, mem.len(): 0
[2019-05-06T12:21:05Z DEBUG evm::interpreter] [OP] "JUMPI" gas=2588
[2019-05-06T12:21:05Z DEBUG evm::interpreter] [Gas] - 10
[2019-05-06T12:21:05Z TRACE evm::interpreter] store_write: None, mem_written: None, mem.len(): 0
[2019-05-06T12:21:05Z DEBUG evm::interpreter] [OP] "JUMPDEST" gas=2578
[2019-05-06T12:21:05Z DEBUG evm::interpreter] [Gas] - 1
[2019-05-06T12:21:05Z TRACE evm::interpreter] store_write: None, mem_written: None, mem.len(): 0
[2019-05-06T12:21:05Z DEBUG evm::interpreter] [OP] "PUSH1" gas=2577
[2019-05-06T12:21:05Z DEBUG evm::interpreter] [Gas] - 3
[2019-05-06T12:21:05Z TRACE evm::interpreter] store_write: None, mem_written: None, mem.len(): 0
[2019-05-06T12:21:05Z DEBUG evm::interpreter] [OP] "CALLDATALOAD" gas=2574
[2019-05-06T12:21:05Z DEBUG evm::interpreter] [Gas] - 3
[2019-05-06T12:21:05Z TRACE evm::interpreter] store_write: None, mem_written: None, mem.len(): 0
[2019-05-06T12:21:05Z DEBUG evm::interpreter] [OP] "PUSH1" gas=2571
[2019-05-06T12:21:05Z DEBUG evm::interpreter] [Gas] - 3
[2019-05-06T12:21:05Z TRACE evm::interpreter] store_write: None, mem_written: None, mem.len(): 0
[2019-05-06T12:21:05Z DEBUG evm::interpreter] [OP] "CALLDATALOAD" gas=2568
[2019-05-06T12:21:05Z DEBUG evm::interpreter] [Gas] - 3
[2019-05-06T12:21:05Z TRACE evm::interpreter] store_write: None, mem_written: None, mem.len(): 0

[2019-05-06T12:21:05Z DEBUG evm::interpreter] [OP] "SSTORE" gas=2565
`[2019-05-06T12:21:05Z TRACE evm::interpreter::gasometer] Error: Out of gas ...`
`[2019-05-06T12:21:05Z DEBUG core_executor::executive] state.revert_to_checkpoint`
`[2019-05-06T12:21:05Z TRACE evm::interpreter] store_write: None, mem_written: Some((987654, 0)), mem.len(): 64`

[2019-05-06T12:21:05Z DEBUG evm::interpreter] [OP] "PUSH1" gas=268755
[2019-05-06T12:21:05Z DEBUG evm::interpreter] [Gas] - 3
[2019-05-06T12:21:05Z TRACE evm::interpreter] store_write: None, mem_written: None, mem.len(): 64
[2019-05-06T12:21:05Z DEBUG evm::interpreter] [OP] "SSTORE" gas=268752
[2019-05-06T12:21:05Z DEBUG evm::interpreter] [Gas] - 5000
[2019-05-06T12:21:05Z DEBUG core_executor::state] state.set_storage address=0x095e7baea6a6c7c4c2dfeb977efac326af552d87 key=0x0000000000000000000000000000000000000000000000000000000000000000 value=0x0000000000000000000000000000000000000000000000000000000000000000
```

**Comment by kaikai1024** [comment]
修正是改了哪里？

**Comment by ouwenkg** [comment]
> 修正是改了哪里？

加了一个判断条件，虽然不容易触发到，但可以在 cita 上修一下。

**Comment by kaikai1024** [comment]
ok.
修正一下吧
