### ISSUE TITLE
feature request: auto display the module version info when the program got panic

### ISSUE THREAD

**Issue by rainchen** [cryptape/cita#454]
for example:

```
2019-04-11T17:20:07.718331067+00:00 - INFO - receive_new_status Bft { h: 122601, r: 0, s: 8 } get new chain status h: 122601, r: 0, cost time: 11.606635874s
2019-04-11T17:20:07.721921531+00:00 - INFO - receive_new_status Bft { h: 122602, r: 0, s: 8 } get new chain status h: 122602, r: 0, cost time: 11.610226396s
2019-04-11T17:20:08.079598058+00:00 - ERROR -
============================
stack backtrace:
   0:     0x55c4aaaddb3d - backtrace::backtrace::trace::hb8d08f317ffdbb76
   1:     0x55c4aaadcd52 - <backtrace::capture::Backtrace as core::default::Default>::default::hc15511ee717eefc8
   2:     0x55c4aaadcdc9 - backtrace::capture::Backtrace::new::hffa0563475b270c1
   3:     0x55c4aaadc000 - panic_hook::panic_hook::hfada2be48bd7e1fa
   4:     0x55c4aaadbd38 - core::ops::function::Fn::call::hb4cc12001ad3eb7f
   5:     0x55c4aadf3686 - std::panicking::rust_panic_with_hook::hde420d6fd4455550
                        at libstd/panicking.rs:480
   6:     0x55c4aadf3417 - std::panicking::begin_panic::h88052f2b1cba5fd8
                        at libstd/panicking.rs:410
   7:     0x55c4aadde4d8 - std::sys::unix::time::inner::Instant::sub_instant::{{closure}}::he0ec527e5e9a153a
                        at libstd/sys/unix/time.rs:292
   8:     0x55c4aade2af3 - <core::result::Result<T, E>>::unwrap_or_else::hd07ab19b475edfd7
                        at libcore/result.rs:774
                         - std::sys::unix::time::inner::Instant::sub_instant::h973008b5cc7805aa
                        at libstd/sys/unix/time.rs:291
                         - std::time::Instant::duration_since::h584fb99ba8cdb997
                        at libstd/time.rs:185
                         - <std::time::Instant as core::ops::arith::Sub>::sub::hb6367386ef7e847a
                        at libstd/time.rs:250
   9:     0x55c4aaa4883a - cita_bft::core::votetime::WaitTimer::start::h6b11c6307ef4683c
  10:     0x55c4aaa7720e - std::sys_common::backtrace::__rust_begin_short_backtrace::h0774dcaae6f9e79a
  11:     0x55c4aaa7870b - std::panicking::try::do_call::h01339b552c28a39e
  12:     0x55c4aae03339 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:102
  13:     0x55c4aaa7bbbf - <F as alloc::boxed::FnBox<A>>::call_box::h6dee667ab4c2a062
  14:     0x55c4aadf0add - <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + 'a)> as core::ops::function::FnOnce<A>>::call_once::h9d902c911a417e39
                        at liballoc/boxed.rs:682
                         - std::sys_common::thread::start_thread::h44127e03e78ca137
                        at libstd/sys_common/thread.rs:24
  15:     0x55c4aade1525 - std::sys::unix::thread::Thread::new::thread_start::h8f17b97f2223146c
                        at libstd/sys/unix/thread.rs:90
  16:     0x7ff26b02b6da - start_thread
  17:     0x7ff26ab3c88e - __clone
  18:                0x0 - <unknown>

position:
Thread <unnamed> panicked at specified instant was later than self, libstd/sys/unix/time.rs:292


There is a bug on cita-bft v0.21.1
Please report it at:

    https://github.com/cryptape/cita/issues/new

============================


```

added this info:

**There is a bug on cita-bft v0.21.1**

so that dev can aware clearly which version is it.

**Comment by kaikai1024** [comment]
The version is a must-have info when users need to report a bug.

Why not run the `bin/cita-bft --version`?

I'm not sure about this is a should-have feature.

**Comment by rainchen** [comment]
According to my past experience, users usually posted their backtrace info(or took a screenshot for it) and the first question developer will ask is "which version you're using?".

“Tell, don't ask". If the version info is a must mentioned info, why not let it automatically, initiatively expose in the right place?

This is `nice-have` feature, it not so necessary but will let users have less depression when having problems with a not familiar software.

**Comment by kaikai1024** [comment]
ok, I accept that and will research it first.

**Comment by jerry-yu** [comment]
another way to know this
