### ISSUE TITLE
cita create node config failed

### ISSUE THREAD

**Issue by u2** [cryptape/cita#465]
## Description

```bash
➜  install git:(develop) bin/cita bebop create --super_admin "0x4b5ae4567ad5d9fb92bc9afd6a657e6fa13a2523" --nodes "127.0.0.1:4000,127.0.0.1:4001,127.0.0.1:4002,127.0.0.1:4003"
Traceback (most recent call last):
  File "/home/u2/cryptape/cita/target/install/scripts/create_cita_config.py", line 12, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
➜  install git:(develop) bin/cita create --super_admin "0x4b5ae4567ad5d9fb92bc9afd6a657e6fa13a2523" --nodes "127.0.0.1:4000,127.0.0.1:4001,127.0.0.1:4002,127.0.0.1:4003" 
Start docker container cita_run_container ...
WARNING: Published ports are discarded when using host network mode
034a65872a8b93a766ee6c6bfd405ff68d40adfc05572c66e898a3d7869ea40b
Initializing chain from provided state
INFO:cita.block	Block pre-sealed, 2246273 quota used 
INFO:cita.chain	Adding to head head=4c29c1f1
Saved 3 address change logs
INFO:cita.chain	Added block 1 (4c21214d) with 1 txs and 2246273 quota
```

## Steps to Reproduce

1. make release
2. cd target/install
```
➜  install git:(develop) ls
bin  resource  scripts
```
3. 
```
➜  install git:(develop) bin/cita bebop create --super_admin "0x4b5ae4567ad5d9fb92bc9afd6a657e6fa13a2523" --nodes "127.0.0.1:4000,127.0.0.1:4001,127.0.0.1:4002,127.0.0.1:4003"
Traceback (most recent call last):
  File "/home/u2/cryptape/cita/target/install/scripts/create_cita_config.py", line 12, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
➜  install git:(develop) bin/cita create --super_admin "0x4b5ae4567ad5d9fb92bc9afd6a657e6fa13a2523" --nodes "127.0.0.1:4000,127.0.0.1:4001,127.0.0.1:4002,127.0.0.1:4003" 
Start docker container cita_run_container ...
WARNING: Published ports are discarded when using host network mode
034a65872a8b93a766ee6c6bfd405ff68d40adfc05572c66e898a3d7869ea40b
Initializing chain from provided state
INFO:cita.block	Block pre-sealed, 2246273 quota used 
```

**Expected behavior**: [What you expect to happen]

**Actual behavior**: [What actually happens]

**Reproduce how often**: [What percentage of the time does it reproduce?]

## Versions

```
➜  install git:(develop) git show HEAD | cat
commit a7265b80193ad239a7abb06422c9660ffd821e04
Merge: 6933a6b 051431d
Author: kaikai <kaikaifeng1024@gmail.com>
Date:   Tue Apr 16 12:08:49 2019 +0800

    Merge pull request #462 from ouwenkg/update_last_hash_test_panic
    
    Fix last hashes panic test
```

## Additional Information

[Any other information which would be helpful to reproduce the issue].

**Comment by kaikai1024** [comment]
The details of new usage of `bin/cita` at #334 .

Here is an example to use `bebop`:
* `.bin/cita-env`
* `bin/cita bebop setup test-chain/0`
* `bin/cita bebop start test-chain/0`

So it's directly to run the command without the docker when you use `bebop`.

And you should ensure your environment of your own pc is ok for running CITA.

**Comment by u2** [comment]
Sorry, I make a mistake. I thought to run with the docker when using bebop. :cry:

**Comment by kaikai1024** [comment]
> install git:(develop) bin/cita create --super_admin "0x4b5ae4567ad5d9fb92bc9afd6a657e6fa13a2523" --nodes "127.0.0.1:4000,127.0.0.1:4001,127.0.0.1:4002,127.0.0.1:4003" 
Start docker container cita_run_container ...

You should do it like this or install the dependencies of `bin/cita create`, then use `bebop`

**Comment by u2** [comment]
After generating the test-node config:

```
➜  install git:(develop) bin/cita setup test-chain/0
➜  install git:(develop) bin/cita setup test-chain/1
Error: unable to connect to node 'rabbit@u2-ThinkPad-T470p': nodedown

DIAGNOSTICS
===========

attempted to contact: ['rabbit@u2-ThinkPad-T470p']

rabbit@u2-ThinkPad-T470p:
  * connected to epmd (port 4369) on u2-ThinkPad-T470p
  * epmd reports node 'rabbit' running on port 25672
  * TCP connection succeeded but Erlang distribution failed

  * Authentication failed (rejected by the remote node), please check the Erlang cookie


current node details:
- node name: 'rabbitmq-cli-43@u2-ThinkPad-T470p'
- home dir: /var/lib/rabbitmq
- cookie hash: AHf3h0LdcnTKNAU/wWX3Kw==

Error: unable to connect to node 'rabbit@u2-ThinkPad-T470p': nodedown

DIAGNOSTICS
===========

attempted to contact: ['rabbit@u2-ThinkPad-T470p']

rabbit@u2-ThinkPad-T470p:
  * connected to epmd (port 4369) on u2-ThinkPad-T470p
  * epmd reports node 'rabbit' running on port 25672
  * TCP connection succeeded but Erlang distribution failed

  * Authentication failed (rejected by the remote node), please check the Erlang cookie


current node details:
- node name: 'rabbitmq-cli-03@u2-ThinkPad-T470p'
- home dir: /var/lib/rabbitmq
- cookie hash: AHf3h0LdcnTKNAU/wWX3Kw==
```

**Comment by kaikai1024** [comment]
Would you please to try to remove the image and run the `setup` again?

**Comment by kaikai1024** [comment]
> rm -rf test-chain

No need to do this. now, you have to create cita config again.

> What's the meaning of remove the image?

sorry, remove the container.

* `docker ps`
* `docker rm xxx -f`
* `bin/cita setup xx`

**Comment by u2** [comment]
```
docker rm xxx -f
```
It works. But I need to do it every time when `cita setup`.

**Comment by kaikai1024** [comment]
> But I need to do it every time when cita setup.

actually, you don't need to do this every time.

I guess rabbitmq got something wrong when you mixed the `bebop`.

Remove the container just gives you a change to do it from a clean environment.

Just follow the steps:

* `create`
* `setup`
* `start`
