### ISSUE TITLE
cita-network run crash with unknown reason

### ISSUE THREAD

**Issue by leeyr338** [cryptape/cita#472]
## Description
cita-network run crash with unknown reason

## Steps to Reproduce
1. [First Step]
  Run CITA with 8 nodes (6 consensus nodes among them).

2. [Second Step]
 About 2 days later, some cita-network run **crash** , and  get the exception message :

```
2019-04-12T11:48:14.750046808+00:00 - INFO - current: 186469, sync_end: 0, global: 186469, sync: false
2019-04-12T11:48:15.867744083+00:00 - ERROR -
============================
stack backtrace:
   0:     0x564ea618602d - backtrace::backtrace::trace::ha7ea0dc8c4985d06
   1:     0x564ea6185242 - <backtrace::capture::Backtrace as core::default::Default>::default::hde34b74397cf2efe
   2:     0x564ea61852b9 - backtrace::capture::Backtrace::new::h3368ee86041b699c
   3:     0x564ea61844f0 - panic_hook::panic_hook::hbff042233c64bd3a
   4:     0x564ea6184228 - core::ops::function::Fn::call::h4f69f13534c1b85e
   5:     0x564ea621a036 - std::panicking::rust_panic_with_hook::hde420d6fd4455550
                        at libstd/panicking.rs:480
   6:     0x564ea6219b81 - std::panicking::continue_panic_fmt::h8f394f3c578bcc76
                        at libstd/panicking.rs:390
   7:     0x564ea6219a65 - rust_begin_unwind
                        at libstd/panicking.rs:325
   8:     0x564ea6260cfc - core::panicking::panic_fmt::hca5dc4e8b320bc56
                        at libcore/panicking.rs:77
   9:     0x564ea5d820f9 - core::result::unwrap_failed::h8b3d8cb0f5d49b87
  10:     0x564ea5dd338e - <tentacle::service::Service<T, U>>::listen_poll::hfa30283762c90644
  11:     0x564ea5ddec8a - <tentacle::service::Service<T, U> as futures::stream::Stream>::poll::h7241392be4147e17
  12:     0x564ea5de6683 - <futures::stream::for_each::ForEach<S, F, U> as futures::future::Future>::poll::he02bc6c6dafb441a
  13:     0x564ea6155891 - futures::task_impl::std::set::h7f85ac2afc2241ea
  14:     0x564ea61574b5 - <futures::task_impl::Spawn<T>>::poll_future_notify::hd7b674b70744f79d
  15:     0x564ea615a420 - std::panicking::try::do_call::hc09e6595b99a58b7
  16:     0x564ea6229ce9 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:102
  17:     0x564ea61597cb - tokio_threadpool::task::Task::run::h5855cb0657bc14e6
  18:     0x564ea6150a45 - tokio_threadpool::worker::Worker::run_task::h19b4f7f5647c0a40
  19:     0x564ea61500de - tokio_threadpool::worker::Worker::run::h564e06cfd8d74d22
  20:     0x564ea613ad95 - <std::thread::local::LocalKey<T>>::with::h0a1269984d3b7219
  21:     0x564ea613aee8 - <std::thread::local::LocalKey<T>>::with::h25b7261318ddcc64
  22:     0x564ea613b222 - <std::thread::local::LocalKey<T>>::with::h76f77d5450352eca
  23:     0x564ea613dbed - tokio::runtime::threadpool::builder::Builder::build::{{closure}}::ha99ff06714a9d7ea
  24:     0x564ea615821c - <std::thread::local::LocalKey<T>>::with::h1acb52d68472f6c1
  25:     0x564ea615837e - <std::thread::local::LocalKey<T>>::with::h23ef2caaf0a572ce
  26:     0x564ea6158f01 - std::sys_common::backtrace::__rust_begin_short_backtrace::hc232df4f4afb351e
  27:     0x564ea615a3db - std::panicking::try::do_call::h9615b2f03bc9a44a
  28:     0x564ea6229ce9 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:102
  29:     0x564ea615497f - <F as alloc::boxed::FnBox<A>>::call_box::he3da36bd9e9ca269
  30:     0x564ea621751d - <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + 'a)> as core::ops::function::FnOnce<A>>::call_once::h9d902c911a417e39
                        at liballoc/boxed.rs:682
                         - std::sys_common::thread::start_thread::h44127e03e78ca137
                        at libstd/sys_common/thread.rs:24
  31:     0x564ea6207a65 - std::sys::unix::thread::Thread::new::thread_start::h8f17b97f2223146c
                        at libstd/sys/unix/thread.rs:90
  32:     0x7fd8a79e96da - start_thread
  33:     0x7fd8a74fa88e - __clone
  34:                0x0 - <unknown>

position:
Thread tokio-runtime-worker-1 panicked at called `Result::unwrap()` on an `Err` value: Os { code: 107, kind: NotConnected, message: "Transport endpoint is not connected" }, libcore/result.rs:1009

This is a bug. Please report it at:

    https://github.com/cryptape/cita/issues/new
```

**Expected behavior**: [What you expect to happen]
Working normally.

**Actual behavior**: [What actually happens]
Run crash.

**Reproduce how often**: [What percentage of the time does it reproduce?]
Unknown

## Versions
V0.22.0

**Comment by leeyr338** [comment]
From drift luo:
 这个是之前库处理的一个bug, 现在没有了; 是epoll 上来一个误报的连接, 而实际上没有连上。

解决办法：
 更换 p2p 库。

**Comment by leeyr338** [comment]
Topic in citahub:
https://talk.citahub.com/t/topic/515/8
