### ISSUE TITLE
cita-network crashed unexpected

### ISSUE THREAD

**Issue by timmyz** [cryptape/cita#535]
found following error at cita-network.log
```
2019-04-29T09:37:28.029742127+00:00 - ERROR -
============================
stack backtrace:
   0:     0x55de167f002d - backtrace::backtrace::trace::ha7ea0dc8c4985d06
   1:     0x55de167ef242 - <backtrace::capture::Backtrace as core::default::Default>::default::hde34b74397cf2efe
   2:     0x55de167ef2b9 - backtrace::capture::Backtrace::new::h3368ee86041b699c
   3:     0x55de167ee4f0 - panic_hook::panic_hook::hbff042233c64bd3a
   4:     0x55de167ee228 - core::ops::function::Fn::call::h4f69f13534c1b85e
   5:     0x55de16884036 - std::panicking::rust_panic_with_hook::hde420d6fd4455550
                        at libstd/panicking.rs:480
   6:     0x55de16883b81 - std::panicking::continue_panic_fmt::h8f394f3c578bcc76
                        at libstd/panicking.rs:390
   7:     0x55de16883a65 - rust_begin_unwind
                        at libstd/panicking.rs:325
   8:     0x55de168cacfc - core::panicking::panic_fmt::hca5dc4e8b320bc56
                        at libcore/panicking.rs:77
   9:     0x55de163ec0f9 - core::result::unwrap_failed::h8b3d8cb0f5d49b87
  10:     0x55de1643d38e - <tentacle::service::Service<T, U>>::listen_poll::hfa30283762c90644
  11:     0x55de16448c8a - <tentacle::service::Service<T, U> as futures::stream::Stream>::poll::h7241392be4147e17
  12:     0x55de16450683 - <futures::stream::for_each::ForEach<S, F, U> as futures::future::Future>::poll::he02bc6c6dafb441a
  13:     0x55de167bf891 - futures::task_impl::std::set::h7f85ac2afc2241ea
  14:     0x55de167c14b5 - <futures::task_impl::Spawn<T>>::poll_future_notify::hd7b674b70744f79d
  15:     0x55de167c4420 - std::panicking::try::do_call::hc09e6595b99a58b7
  16:     0x55de16893ce9 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:102
  17:     0x55de167c37cb - tokio_threadpool::task::Task::run::h5855cb0657bc14e6
  18:     0x55de167baa45 - tokio_threadpool::worker::Worker::run_task::h19b4f7f5647c0a40
  19:     0x55de167b9efd - tokio_threadpool::worker::Worker::run::h564e06cfd8d74d22
  20:     0x55de167a4d95 - <std::thread::local::LocalKey<T>>::with::h0a1269984d3b7219
  21:     0x55de167a4ee8 - <std::thread::local::LocalKey<T>>::with::h25b7261318ddcc64
  22:     0x55de167a5222 - <std::thread::local::LocalKey<T>>::with::h76f77d5450352eca
  23:     0x55de167a7bed - tokio::runtime::threadpool::builder::Builder::build::{{closure}}::ha99ff06714a9d7ea
  24:     0x55de167c221c - <std::thread::local::LocalKey<T>>::with::h1acb52d68472f6c1
  25:     0x55de167c237e - <std::thread::local::LocalKey<T>>::with::h23ef2caaf0a572ce
  26:     0x55de167c2f01 - std::sys_common::backtrace::__rust_begin_short_backtrace::hc232df4f4afb351e
  27:     0x55de167c43db - std::panicking::try::do_call::h9615b2f03bc9a44a
  28:     0x55de16893ce9 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:102
  29:     0x55de167be97f - <F as alloc::boxed::FnBox<A>>::call_box::he3da36bd9e9ca269
  30:     0x55de1688151d - <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + 'a)> as core::ops::function::FnOnce<A>>::call_once::h9d902c911a417e39
                        at liballoc/boxed.rs:682
                         - std::sys_common::thread::start_thread::h44127e03e78ca137
                        at libstd/sys_common/thread.rs:24
  31:     0x55de16871a65 - std::sys::unix::thread::Thread::new::thread_start::h8f17b97f2223146c
                        at libstd/sys/unix/thread.rs:90
  32:     0x7fcee5da66da - start_thread
  33:     0x7fcee58b788e - __clone
  34:                0x0 - <unknown>

position:
Thread tokio-runtime-worker-0 panicked at called `Result::unwrap()` on an `Err` value: Os { code: 107, kind: NotConnected, message: "Transport endpoint is not connected" }, libcore/result.rs:1009
```

**Comment by kaikai1024** [comment]
What's the version and would you like to add some descriptions about the process?
Thanks!

**Comment by timmyz** [comment]
version: 0.22
i just use cita-op-helper to dump the tar file, please refer to the attachment.
[cita_info.tar.gz](https://github.com/cryptape/cita/files/3130300/cita_info.tar.gz)

**Comment by leeyr338** [comment]
This is a known bug in v0.22.0, see

https://github.com/cryptape/cita/issues/472

for more details.

**Comment by timmyz** [comment]
i see. so the only way is to upgrade to 0.23 version?

**Comment by leeyr338** [comment]
I have to say **Yes**.
